<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404165927 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE playing_with_neon_id_seq CASCADE');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c63c0c9956');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c616a2b381');
        $this->addSql('DROP TABLE playing_with_neon');
        $this->addSql('DROP TABLE review');
        $this->addSql('ALTER TABLE reservation DROP created_at');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE playing_with_neon_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE playing_with_neon (id INT DEFAULT nextval(\'playing_with_neon_id_seq\'::regclass) NOT NULL, name TEXT NOT NULL, value REAL DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT DEFAULT NULL, rating INT NOT NULL, book_id INT NOT NULL, user_account_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_794381c616a2b381 ON review (book_id)');
        $this->addSql('CREATE INDEX idx_794381c63c0c9956 ON review (user_account_id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c63c0c9956 FOREIGN KEY (user_account_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c616a2b381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }
}
