<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402082301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favoris (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_favoris_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8933C432F68F41F7 ON favoris (user_favoris_id)');
        $this->addSql('CREATE INDEX IDX_8933C432F347EFB ON favoris (produit_id)');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432F68F41F7 FOREIGN KEY (user_favoris_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT fk_29a5ec2779f37ae5');
        $this->addSql('DROP INDEX idx_29a5ec2779f37ae5');
        $this->addSql('ALTER TABLE produit DROP id_user_id');
        $this->addSql('ALTER TABLE produit ALTER prix TYPE INT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C432F68F41F7');
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C432F347EFB');
        $this->addSql('DROP TABLE favoris');
        $this->addSql('ALTER TABLE produit ADD id_user_id INT NOT NULL');
        $this->addSql('ALTER TABLE produit ALTER prix TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT fk_29a5ec2779f37ae5 FOREIGN KEY (id_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_29a5ec2779f37ae5 ON produit (id_user_id)');
    }
}
